defaultContentLanguage = "zh-cn" # 默认语言
defaultContentLanguageInSubdir = true
baseURL = 'https://george-blog.pages.dev' # 你购买的域名
languageCode = 'zh-cn'
title = "George's Blog" # Blog title 
theme = ["https://github.com/miiiku/hugo-theme-kagome"] # 你选择的主题
hasCJKLanguage = true # CJK 为中国, 日本, 韩国的缩写
canonifyurls = true
paginate = 6


[module]
[[module.imports]]
    path = 'https://github.com/miiiku/hugo-theme-kagome' # 使用 hugo mod 管理主题
